SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[___test] (
		[RowId]                       [varchar](max) COLLATE Latin1_General_CI_AS NULL,
		[TaskId]                      [varchar](max) COLLATE Latin1_General_CI_AS NULL,
		[WD_Url]                      [varchar](max) COLLATE Latin1_General_CI_AS NULL,
		[vol continu]                 [varchar](max) COLLATE Latin1_General_CI_AS NULL,
		[ploegendienst]               [varchar](max) COLLATE Latin1_General_CI_AS NULL,
		[ploegendiensten]             [varchar](max) COLLATE Latin1_General_CI_AS NULL,
		[avonddienst]                 [varchar](max) COLLATE Latin1_General_CI_AS NULL,
		[avonddiensten]               [varchar](max) COLLATE Latin1_General_CI_AS NULL,
		[middagdienst]                [varchar](max) COLLATE Latin1_General_CI_AS NULL,
		[middagdiensten]              [varchar](max) COLLATE Latin1_General_CI_AS NULL,
		[ochtenddiens]                [varchar](max) COLLATE Latin1_General_CI_AS NULL,
		[ochtenddiensten]             [varchar](max) COLLATE Latin1_General_CI_AS NULL,
		[shifts]                      [varchar](max) COLLATE Latin1_General_CI_AS NULL,
		[magazijn]                    [varchar](max) COLLATE Latin1_General_CI_AS NULL,
		[ware housing]                [varchar](max) COLLATE Latin1_General_CI_AS NULL,
		[extra personeel]             [varchar](max) COLLATE Latin1_General_CI_AS NULL,
		[klantenservice]              [varchar](max) COLLATE Latin1_General_CI_AS NULL,
		[customer service]            [varchar](max) COLLATE Latin1_General_CI_AS NULL,
		[customer center]             [varchar](max) COLLATE Latin1_General_CI_AS NULL,
		[24 uur per dag]              [varchar](max) COLLATE Latin1_General_CI_AS NULL,
		[7 dagen per week]            [varchar](max) COLLATE Latin1_General_CI_AS NULL,
		[07/24/2018 00:00:00]         [varchar](max) COLLATE Latin1_General_CI_AS NULL,
		[noodservice]                 [varchar](max) COLLATE Latin1_General_CI_AS NULL,
		[operational excellence]      [varchar](max) COLLATE Latin1_General_CI_AS NULL,
		[altijd bereikbaar]           [varchar](max) COLLATE Latin1_General_CI_AS NULL,
		[vakantiewerk]                [varchar](max) COLLATE Latin1_General_CI_AS NULL,
		[vakantiekracht]              [varchar](max) COLLATE Latin1_General_CI_AS NULL,
		[vakantiekrachten]            [varchar](max) COLLATE Latin1_General_CI_AS NULL,
		[seizoenswerk]                [varchar](max) COLLATE Latin1_General_CI_AS NULL,
		[oproepkracht]                [varchar](max) COLLATE Latin1_General_CI_AS NULL,
		[oproepkrachten]              [varchar](max) COLLATE Latin1_General_CI_AS NULL,
		[ploegentoeslag]              [varchar](max) COLLATE Latin1_General_CI_AS NULL,
		[flexibele werktijden]        [varchar](max) COLLATE Latin1_General_CI_AS NULL,
		[flexibel dienstverband]      [varchar](max) COLLATE Latin1_General_CI_AS NULL,
		[900]                         [varchar](max) COLLATE Latin1_General_CI_AS NULL,
		[800]                         [varchar](max) COLLATE Latin1_General_CI_AS NULL,
		[Som]                         [varchar](max) COLLATE Latin1_General_CI_AS NULL,
		[HAS_SIZOKEY_Value]           [varchar](max) COLLATE Latin1_General_CI_AS NULL,
		[HAS_SIZOKEY_Note]            [varchar](max) COLLATE Latin1_General_CI_AS NULL,
		[HAS_CHAT_Value]              [varchar](max) COLLATE Latin1_General_CI_AS NULL,
		[HAS_CHAT_Note]               [varchar](max) COLLATE Latin1_General_CI_AS NULL,
		[HAS_CONTACT_US_Value]        [varchar](max) COLLATE Latin1_General_CI_AS NULL,
		[HAS_CONTACT_US_Note]         [varchar](max) COLLATE Latin1_General_CI_AS NULL,
		[HAS_PHONE_NUMBERS_Value]     [varchar](max) COLLATE Latin1_General_CI_AS NULL,
		[HAS_PHONE_NUMBERS_Note]      [varchar](max) COLLATE Latin1_General_CI_AS NULL,
		[HAS_PAKETBEZORGER_Value]     [varchar](max) COLLATE Latin1_General_CI_AS NULL,
		[HAS_PAKETBEZORGER_Note]      [varchar](max) COLLATE Latin1_General_CI_AS NULL,
		[SIZO_AWP_Value]              [varchar](max) COLLATE Latin1_General_CI_AS NULL,
		[SIZO_AWP_Note]               [varchar](max) COLLATE Latin1_General_CI_AS NULL,
		[IS_WEBSHOP_Value]            [varchar](max) COLLATE Latin1_General_CI_AS NULL,
		[IS_WEBSHOP_Note]             [varchar](max) COLLATE Latin1_General_CI_AS NULL,
		[CI_BronBestand]              [varchar](max) COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[___test] SET (LOCK_ESCALATION = TABLE)
GO
