SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [tSQLt].[Private_NewTestClassList] (
		[ClassName]     [nvarchar](450) COLLATE Latin1_General_CI_AS NOT NULL,
		CONSTRAINT [PK__Private___F8BF561A648376FB]
		PRIMARY KEY
		CLUSTERED
		([ClassName])
	ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [tSQLt].[Private_NewTestClassList] SET (LOCK_ESCALATION = TABLE)
GO
